import express from "express";
import cors from "cors";
import multer from "multer";
const app=express(), upload=multer({storage:multer.memoryStorage(),limits:{fileSize:20*1024*1024}});
app.use(cors()); app.use(express.json({limit:"5mb"})); app.use(express.static("public"));
const PORT=process.env.PORT||3000, EARTH=6371000;
const hav=(a,b)=>{const p=Math.PI/180,la=(b.lat-a.lat)*p,lo=(b.lon-a.lon)*p,x=Math.sin(la/2)**2+Math.cos(a.lat*p)*Math.cos(b.lat*p)*Math.sin(lo/2)**2;return 2*EARTH*Math.asin(Math.sqrt(x))};
const med=a=>{a=a.filter(Number.isFinite).sort((x,y)=>x-y);if(!a.length)return 0;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2};
function parseGPX(x){const o=[],r=/<trkpt\b([^>]*)>([\s\S]*?)<\/trkpt>/gi;let m;while(m=r.exec(x)){const a=/\blat="([^"]+)"/i.exec(m[1]),b=/\blon="([^"]+)"/i.exec(m[1]),t=/<time>\s*([^<]+)\s*<\/time>/i.exec(m[2]);if(a&&b)o.push({lat:+a[1],lon:+b[1],time:t?new Date(t[1]):null})}return o}
function googleCoords(s){let u;try{u=new URL(s)}catch{throw Error("Ugyldigt Google Maps-link.")}const out=[],add=(a,b)=>{a=+a;b=+b;if(Number.isFinite(a)&&Number.isFinite(b)&&Math.abs(a)<=90&&Math.abs(b)<=180)out.push({lat:a,lon:b})};const d=u.pathname.match(/\/dir\/(.+)/i);if(d)for(const q of d[1].split("/")){const m=q.match(/(-?\d+(?:\.\d+)?),\s*(-?\d+(?:\.\d+)?)/);if(m)add(m[1],m[2])}for(const k of ["origin","destination","waypoints"]){const v=u.searchParams.get(k);if(v)for(const q of v.split("|")){const m=q.match(/(-?\d+(?:\.\d+)?),\s*(-?\d+(?:\.\d+)?)/);if(m)add(m[1],m[2])}}return out.filter((p,i,a)=>i===a.findIndex(q=>Math.abs(q.lat-p.lat)<1e-8&&Math.abs(q.lon-p.lon)<1e-8))}
async function osrm(ps){if(ps.length<2)throw Error("Google-linket indeholder ikke nok koordinater.");const c=ps.map(p=>`${p.lon},${p.lat}`).join(";"),u=`https://router.project-osrm.org/route/v1/driving/${c}?overview=full&geometries=geojson`;const r=await fetch(u,{headers:{"User-Agent":"GPX-Reconstructor/1.0"}});if(!r.ok)throw Error("Routing-tjenesten kunne ikke kontaktes.");const d=await r.json();if(d.code!=="Ok")throw Error("Kunne ikke finde en rute.");return d.routes[0].geometry.coordinates.map(([lon,lat])=>({lat,lon}))}
function sample(route,sp){const o=[route[0]];let carry=0;for(let i=1;i<route.length;i++){let a=route[i-1],b=route[i],seg=hav(a,b);while(carry+seg>=sp&&seg>0){const t=(sp-carry)/seg,p={lat:a.lat+(b.lat-a.lat)*t,lon:a.lon+(b.lon-a.lon)*t};o.push(p);a=p;seg=hav(a,b);carry=0}carry+=seg}if(hav(o.at(-1),route.at(-1))>.5)o.push(route.at(-1));return o}
function times(orig,start,pts,endISO){const hist=[];for(let i=1;i<=start;i++){const dt=(orig[i].time-orig[i-1].time)/1000,ds=hav(orig[i-1],orig[i]);if(dt>0&&ds>1)hist.push(ds/dt)}const speed=med(hist)||5,target=new Date(endISO),total=(target-orig[start].time)/1000;if(!Number.isFinite(target.getTime())||total<=0)throw Error("Sluttidspunkt skal være efter sidste eksisterende punkt.");let dist=0;for(let i=1;i<pts.length;i++)dist+=hav(pts[i-1],pts[i]);if(dist<=0)throw Error("Ruten er for kort.");const raw=dist/speed,scale=total/raw,out=[orig[start].time];let e=0;for(let i=1;i<pts.length;i++){e+=hav(pts[i-1],pts[i])/speed*scale;out.push(i===pts.length-1?target:new Date(orig[start].time.getTime()+e*1000))}return out}
app.post("/api/route-from-google",async(req,res)=>{try{const c=googleCoords(req.body.url||"");if(c.length<2)throw Error("Kunne ikke læse start og destination. Brug et fuldt Google Maps rute-link.");res.json({route:await osrm(c)})}catch(e){res.status(400).json({error:e.message})}});
app.post("/api/reconstruct",upload.single("gpx"),async(req,res)=>{try{if(!req.file)throw Error("Upload en GPX-fil.");const xml=req.file.buffer.toString(),orig=parseGPX(xml);if(orig.length<3)throw Error("GPX-filen har for få trackpoints.");const lat=+req.body.endLat,lon=+req.body.endLon;if(!Number.isFinite(lat)||!Number.isFinite(lon))throw Error("Ugyldige slutkoordinater.");let route=JSON.parse(req.body.route||"[]");if(route.length<2)throw Error("Tegn eller hent først en rute.");route=route.map(p=>({lat:+p.lat,lon:+p.lon}));route[route.length-1]={lat,lon};const sp=med(orig.slice(1).map((p,i)=>hav(orig[i],p)).filter(d=>d>1))||10,pts=sample(route,sp);pts[0]={lat:orig.at(-1).lat,lon:orig.at(-1).lon};pts.at(-1)={lat,lon};const ts=times(orig,orig.length-1,pts,req.body.endTime);const tags=pts.slice(1).map((p,i)=>`<trkpt lat="${p.lat.toFixed(8)}" lon="${p.lon.toFixed(8)}"><time>${ts[i+1].toISOString()}</time></trkpt>`).join(""),matches=[...xml.matchAll(/<trkpt\b[^>]*>[\s\S]*?<\/trkpt>/gi)],m=matches.at(-1),at=m.index+m[0].length;res.setHeader("Content-Type","application/gpx+xml; charset=utf-8");res.setHeader("Content-Disposition",'attachment; filename="reconstructed.gpx"');res.send(xml.slice(0,at)+tags+xml.slice(at))}catch(e){res.status(400).json({error:e.message})}});
app.get("/api/health",(q,r)=>r.json({ok:true}));app.listen(PORT,()=>console.log("Listening on "+PORT));
