import express from 'express';
import cors from 'cors';
import multer from 'multer';
import polyline from '@mapbox/polyline';
import fs from 'fs/promises';
import os from 'os';
import path from 'path';
import { fileURLToPath } from 'url';
const __dirname=path.dirname(fileURLToPath(import.meta.url));
const app=express(), upload=multer({dest:path.join(os.tmpdir(),'gpx-fixer'),limits:{fileSize:20*1024*1024}});
app.use(cors()); app.use(express.static(path.join(__dirname,'public')));
const KEY=process.env.GOOGLE_MAPS_API_KEY, PORT=Number(process.env.PORT||3000);
const hav=(a,b)=>{const R=6371000,p1=a.lat*Math.PI/180,p2=b.lat*Math.PI/180,dp=(b.lat-a.lat)*Math.PI/180,dl=(b.lon-a.lon)*Math.PI/180,x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(x))};
function coord(v){const m=String(v||'').trim().match(/^(-?\d+(?:\.\d+)?)\s*,\s*(-?\d+(?:\.\d+)?)$/);if(!m)return null;const lat=+m[1],lon=+m[2];return lat>=-90&&lat<=90&&lon>=-180&&lon<=180?{lat,lon}:null}
function clean(v){return decodeURIComponent(String(v).replace(/\+/g,' ')).trim()}
function parseMaps(raw){let u;try{u=new URL(raw)}catch{throw Error('Google Maps-linket er ikke en gyldig URL.')}let o={origin:null,destination:null,waypoints:[],travelMode:'DRIVE'}; if(u.searchParams.get('origin'))o.origin=clean(u.searchParams.get('origin'));if(u.searchParams.get('destination'))o.destination=clean(u.searchParams.get('destination'));let w=u.searchParams.get('waypoints');if(w)o.waypoints=w.split('|').map(clean).filter(Boolean);let tm=u.searchParams.get('travelmode');if(tm==='walking')o.travelMode='WALK';else if(tm==='bicycling')o.travelMode='BICYCLE';const parts=u.pathname.split('/').filter(Boolean),i=parts.indexOf('dir');if(i>=0){const a=parts.slice(i+1).map(clean).filter(x=>x&&!/^@|^data=/.test(x));if(!o.origin&&a[0])o.origin=a[0];if(!o.destination&&a[1])o.destination=a[1]}o.origin=coord(o.origin)||o.origin;o.destination=coord(o.destination)||o.destination;o.waypoints=o.waypoints.map(x=>coord(x)||x);return o}
function wp(p){return typeof p==='object'?{location:{latLng:{latitude:p.lat,longitude:p.lon}}}:{address:p}}
async function route(x){if(!KEY)throw Error('GOOGLE_MAPS_API_KEY mangler. Kopiér .env.example til .env og indsæt din nøgle.');if(!x.origin||!x.destination)throw Error('Kunne ikke finde både start og destination i linket. Brug et Google Maps Directions-link.');const r=await fetch('https://routes.googleapis.com/directions/v2:computeRoutes',{method:'POST',headers:{'Content-Type':'application/json','X-Goog-Api-Key':KEY,'X-Goog-FieldMask':'routes.distanceMeters,routes.duration,routes.polyline.encodedPolyline'},body:JSON.stringify({origin:wp(x.origin),destination:wp(x.destination),intermediates:x.waypoints.map(wp),travelMode:x.travelMode,routingPreference:'TRAFFIC_UNAWARE',polylineQuality:'HIGH_QUALITY',polylineEncoding:'ENCODED_POLYLINE'})});const d=await r.json();if(!r.ok)throw Error(d.error?.message||`Routes API-fejl ${r.status}`);const e=d.routes?.[0]?.polyline?.encodedPolyline;if(!e)throw Error('Routes API returnerede ingen rute.');return polyline.decode(e).map(([lat,lon])=>({lat,lon}))}
function gpx(xml){const out=[],re=/<trkpt\b([^>]*)>([\s\S]*?)<\/trkpt\s*>/gi;let m;while(m=re.exec(xml)){const a=m[1],lat=a.match(/\blat\s*=\s*"([^"]+)"/i),lon=a.match(/\blon\s*=\s*"([^"]+)"/i);if(!lat||!lon)continue;const t=m[2].match(/<time[^>]*>\s*([^<]+?)\s*<\/time>/i);out.push({lat:+lat[1],lon:+lon[1],time:t?.[1]||null})}if(!out.length)throw Error('GPX-filen indeholder ingen trackpoints.');return out}
const med=a=>{a=a.filter(Number.isFinite).sort((x,y)=>x-y);return a.length?a[Math.floor(a.length/2)]:null};
function nearest(p,r){let best={distance:Infinity,index:0,t:0,point:r[0]};for(let i=0;i<r.length-1;i++){const k=Math.cos(p.lat*Math.PI/180),ax=r[i].lon*k,ay=r[i].lat,bx=r[i+1].lon*k,by=r[i+1].lat,px=p.lon*k,py=p.lat,dx=bx-ax,dy=by-ay;let t=((px-ax)*dx+(py-ay)*dy)/(dx*dx+dy*dy||1);t=Math.max(0,Math.min(1,t));const q={lat:r[i].lat+t*(r[i+1].lat-r[i].lat),lon:r[i].lon+t*(r[i+1].lon-r[i].lon)},d=hav(p,q);if(d<best.distance)best={distance:d,index:i,t,point:q}}return best}
function reconstruct(o,r,target){const cum=[0];for(let i=1;i<r.length;i++)cum.push(cum[i-1]+hav(r[i-1],r[i]));const a=nearest(o.at(-1),r),b=nearest(target,r),start=cum[a.index]+hav(r[a.index],a.point),end=cum[b.index]+hav(r[b.index],b.point);if(end<=start)throw Error('Slutpunktet ligger ikke efter GPX-slutpunktet på ruten.');const ds=[],dts=[],speeds=[];for(let i=1;i<o.length;i++){const d=hav(o[i-1],o[i]);if(d>.1)ds.push(d);if(o[i-1].time&&o[i].time){const x=Date.parse(o[i-1].time),y=Date.parse(o[i].time);if(y>x)dts.push((y-x)/1000),speeds.push(d/((y-x)/1000))}}const spacing=Math.max(.5,med(ds)||5),interval=med(dts)||1,speed=med(speeds),n=Math.max(1,Math.ceil((end-start)/spacing));const at=s=>{let lo=0,hi=cum.length-1;while(lo<hi){const m=Math.floor((lo+hi)/2);if(cum[m]<s)lo=m+1;else hi=m}if(lo===0)return r[0];const i=lo,A=cum[i-1],B=cum[i],f=B===A?0:(s-A)/(B-A);return{lat:r[i-1].lat+f*(r[i].lat-r[i-1].lat),lon:r[i-1].lon+f*(r[i].lon-r[i-1].lon)}};let prev=o.at(-1),elapsed=0;const startMs=o.at(-1).time?Date.parse(o.at(-1).time):Date.now(),pts=[];for(let i=1;i<=n;i++){const p=i===n?target:at(start+(end-start)*i/n),d=hav(prev,p);elapsed+=speed&&speed>.1?d/speed:interval;pts.push({...p,time:new Date(startMs+elapsed*1000).toISOString()});prev=p}return pts}
function esc(s){return String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&apos;')}
function append(xml,pts){if(!/<\/trkseg\s*>/i.test(xml))throw Error('GPX-filen mangler </trkseg>.');const s=pts.map(p=>`    <trkpt lat="${p.lat.toFixed(14)}" lon="${p.lon.toFixed(14)}"><time>${esc(p.time)}</time></trkpt>`).join('\n');return xml.replace(/<\/trkseg\s*>/i,`${s}\n  </trkseg>`) }
app.post('/api/fix',upload.single('gpx'),async(req,res)=>{let f=req.file?.path;try{if(!req.file)throw Error('Upload en GPX-fil.');const target=coord(req.body.target);if(!target)throw Error('Slutkoordinater skal være latitude, longitude.');const xml=await fs.readFile(f,'utf8'),orig=gpx(xml),route=await route(parseMaps(req.body.routeUrl)),pts=reconstruct(orig,route,target);res.setHeader('Content-Type','application/gpx+xml');res.setHeader('Content-Disposition','attachment; filename="fixed_'+req.file.originalname.replace(/[^a-zA-Z0-9._-]/g,'_')+'"');res.send(append(xml,pts))}catch(e){res.status(400).json({error:e.message})}finally{if(f)fs.unlink(f).catch(()=>{})}});
app.listen(PORT,()=>console.log(`GPX Fixer: http://localhost:${PORT}`));
